name: Trigger auto deployment for app2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'aca-frontend/**'
    - '.github/workflows/app2-AutoDeployTrigger-486e3087-9365-4011-a851-0413fa622014.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xwang971reg.azurecr.io
          username: ${{ secrets.APP2_REGISTRY_USERNAME }}
          password: ${{ secrets.APP2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xwang971reg.azurecr.io/euaptestimage:${{ github.sha }}
          file: aca-frontend/Dockerfile
          context: aca-frontend/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APP2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n app2 -g rg --server xwang971reg.azurecr.io --username  ${{ secrets.APP2_REGISTRY_USERNAME }} --password ${{ secrets.APP2_REGISTRY_PASSWORD }}
            az containerapp update -n app2 -g rg --image xwang971reg.azurecr.io/euaptestimage:${{ github.sha }}
