name: Trigger auto deployment for containerapp westeuropetest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'aca-frontend/**'
    - '.github/workflows/westeuropetest-AutoDeployTrigger-1bcdde8c-0605-4060-bf57-5179cd1db645.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xwang971reg.azurecr.io
          username: ${{ secrets.WESTEUROPETEST_REGISTRY_USERNAME }}
          password: ${{ secrets.WESTEUROPETEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xwang971reg.azurecr.io/westeuropetest:${{ github.sha }}
          file: aca-frontend/Dockerfile
          context: aca-frontend/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WESTEUROPETEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n westeuropetest -g workerapps-rg-xj --server xwang971reg.azurecr.io --username  ${{ secrets.WESTEUROPETEST_REGISTRY_USERNAME }} --password ${{ secrets.WESTEUROPETEST_REGISTRY_PASSWORD }}
            az containerapp update -n westeuropetest -g workerapps-rg-xj --image xwang971reg.azurecr.io/westeuropetest:${{ github.sha }}
